### ISSUE TITLE
完善字面量翻译机制

### ISSUE THREAD

**Issue by awxiaoxian2020** [ts-zh-docs/community#3]

**Comment by awxiaoxian2020** [comment]
https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/typescriptlang/zh 这个目录的文件里面的字符串是全的吗？烦请社区帮忙看下相关的源码。

**Comment by hanyujie2002** [comment]
The content is not full. See

https://github.com/microsoft/TypeScript-Website/tree/v2/packages/typescriptlang-org/src/copy/en

**Comment by hanyujie2002** [comment]
@awxiaoxian2020

**Comment by awxiaoxian2020** [comment]
The files' count is not sync. I just want to know where is the `key-value` used , in the file. And is it full for single file?

**Comment by awxiaoxian2020** [comment]
It is wrapped by `i()` function.

**Comment by awxiaoxian2020** [comment]
为方便迁移，字面量从现在起不再采用原有机制，直接翻译即可。
